# Build via docker:
# docker build --build-arg cores=8 -t blocknetdx/{{ walletDockerName }}:latest .

FROM ubuntu:{{ buildOS }}

ARG cores=6
ENV ecores=$cores

LABEL wallet={{ walletName }}
LABEL version={{ walletGitTag }}

ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update \
  && apt install -y --no-install-recommends \
     software-properties-common \
     ca-certificates \
     wget curl git vim \
     build-essential libtool autotools-dev automake \
     pkg-config bsdmainutils bison python3 libgmp-dev cmake ninja-build \
{% if apt_extra %}
     {{ apt_extra }} \
{% endif %}
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV DISTDIR=/opt/blockchain/dist

# Build source
RUN mkdir -p /opt/{{ walletLinuxDir }} \
  && mkdir -p /opt/blockchain/config \
  && mkdir -p /opt/blockchain/data \
  && ln -s /opt/blockchain/config /root/.{{ walletLinuxDir }} \
  && cd /opt/{{ walletLinuxDir }} \
{% if git_ref %}
  && git clone --depth 1 {{ walletGitURL }} {{ walletLinuxDir }} \
  && cd {{ walletLinuxDir }} \
  && git fetch --depth 1 origin {{ git_ref }} \
  && git checkout FETCH_HEAD \
  && cd /opt/{{ walletLinuxDir }}/{{ walletLinuxDir }}/ \
{% else %}
  && git clone --depth 1 --branch {{ walletGitTag }} {{ walletGitURL }} {{ walletLinuxDir }} \
  && cd /opt/{{ walletLinuxDir }}/{{ walletLinuxDir }}/ \
{% endif %}
{% if source_subdir %}
  && cd {{ source_subdir }} \
{% endif %}
{% if build_system == 'makefile_unix' %}
  && cd src \
{% for cmd in depends_prep %}
  && {{ cmd }} \
{% endfor %}
  && make "USE_NATIVETOR=-" -f makefile.unix INNOVA_SPINNER=0 -j$ecores \
{% for cmd in post_build %}
  && {{ cmd }} \
{% endfor %}
  && cp {{ walletDaemon }} /usr/bin/ \
  && ln -s {{ walletDaemon }} /usr/bin/{{ walletDaemon[:-1] }}-cli \
{% else %}
  && cd depends \
{% for cmd in depends_prep %}
  && {{ cmd }} \
{% endfor %}
&& make -j$ecores NO_QT=1 \
{% set platformPath = platform_path if platform_path else 'x86_64-pc-linux-gnu' %}
{% if build_system == 'cmake' %}
&& cd .. \
&& mkdir -p build && cd build \
&& cmake -GNinja .. -DCMAKE_TOOLCHAIN_FILE=../cmake/platforms/Linux64.cmake -DCMAKE_TOOLCHAIN_PREFIX=x86_64-pc-linux-gnu -DCMAKE_C_COMPILER={{ cc }} -DCMAKE_CXX_COMPILER={{ cxx }} -DCMAKE_CXX_FLAGS="-Wno-error=return-type" -DBUILD_BITCOIN_QT=OFF -DENABLE_MAN=OFF \
&& ninja -j$ecores \
{% for cmd in post_build %}
&& {{ cmd }} \
{% endfor %}
&& DESTDIR=$DISTDIR ninja install \
{% elif build_system == 'cmake_core' %}
&& cd .. \
&& cmake -B build -DCMAKE_TOOLCHAIN_FILE=depends/{{ platformPath }}/toolchain.cmake -DCMAKE_CXX_FLAGS="-Wno-error=return-type" -DBUILD_TESTS=OFF -DBUILD_BENCH=OFF -DINSTALL_MAN=OFF \
&& cmake --build build -j $ecores \
{% for cmd in post_build %}
&& {{ cmd }} \
{% endfor %}
&& DESTDIR=$DISTDIR cmake --install build \
{% else %}
&& cd .. \
&& chmod +x ./autogen.sh \
&& ./autogen.sh \
&& ./configure CC="{{ cc }}" CXX="{{ cxx }}" CXXFLAGS="-Wno-error=return-type" --with-gui=no --enable-hardening{% if configure_flags %} {{ configure_flags }}{% endif %} --prefix=`pwd`/depends/{{ platformPath }} \
&& make -j$ecores \
{% for cmd in post_build %}
&& {{ cmd }} \
{% endfor %}
&& make install DESTDIR=$DISTDIR \
{% endif %}
  {% if build_system == 'cmake' or build_system == 'cmake_core' %}
  && cp $DISTDIR/usr/local/bin/* /usr/bin/ \
  {% else %}
  && cp $DISTDIR/opt/{{ walletLinuxDir }}/{{ walletLinuxDir }}{% if source_subdir %}/{{ source_subdir }}{% endif %}/depends/{{ platformPath }}/bin/* /usr/bin/ \
  {% endif %}
{% endif %}
  && rm -rf /opt/{{ walletLinuxDir }}/

# Write default {{ walletConfName }} (can be overridden on commandline)
RUN echo "datadir=/opt/blockchain/data  \n\
                                        \n\
dbcache=256                             \n\
maxmempool=512                          \n\
                                        \n\
rpcuser=test                            \n\
rpcpassword=AZErty.1                    \n\
                                        \n\
port={{ walletPort }}                              \n\
rpcport={{ walletRPCPort }}                           \n\
                                        \n\
listen=1                                \n\
txindex=1                               \n\
server=1                                \n\
maxconnections=16                       \n\
{% for addr in addnodes %}addnode={{ addr }}                    \n\
{% endfor %}logtimestamps=1                         \n\
logips=1                                \n\
                                        \n\
rpcallowip=127.0.0.1                    \n\
rpctimeout=30                           \n\
rpcclienttimeout=30                     \n" > /opt/blockchain/config/{{ walletConfName }}

WORKDIR /opt/blockchain/
VOLUME ["/opt/blockchain/config", "/opt/blockchain/data"]

# Port, RPC, Test Port, Test RPC
EXPOSE {{ walletPort }} {{ walletRPCPort }}  {{ testnetPort }}  {{ testnetRPC }}

{% if tail_debuglog %}
# {{ walletName }} daemon logs to debug.log only (fPrintToConsole=false), so
# stream it to stdout via tail -F; daemon stays PID 1 for clean shutdown.
CMD ["/bin/bash", "-c", "tail -F /opt/blockchain/data/debug.log & exec /usr/bin/{{ walletDaemon }} -daemon=0"]
{% elif launch_flags %}
# {{ walletName }} daemon needs extra launch option(s).
CMD ["/usr/bin/{{ walletDaemon }}", "-daemon=0"{% for flag in launch_flags %}, "{{ flag }}"{% endfor %}]
{% else %}
CMD ["/usr/bin/{{ walletDaemon }}", "-daemon=0"]
{% endif %}
